dnaseq = "GCTTGTATGCCGAAACCAAGGCCATCAGTTAATGCAATAGCTAAGTAATAATTCGTCTCTGCCCGAGTGGATGCTTTGTGCGGATGTGTAAGCGCTGTATACTTCAAAAGGCGTCCTCCTAGTAGGAGGATGGACCAATCCGGAGAGAGTCGCCTTGTGTATAACATCGAAACCTCCTGCCCGGTGGGACTAGAATTATCACTTCAACGAGGAGGCTAATCTAGTCAGGATTGGTATTATACCCGCCTCGAGCGAAAAACTCCAGCAATGACAACTCTACGGCGCGGCTACAACTCTTATTACTTGGCGCGTACAAGACTAACGACGGAACGCAGCGCTGAAGCTGTTAACCACTATCTGGTGAGAGCTTGTACGGGAGATGCAAAATTCAGCCCCTCGCCCCACCCAATTAATAGCATTCCACTCCCTTGAACGAGTCGTGGTACTTGGCTCTATTTGACCCATTGACGTGGGGCGCCGTATTCTTGCGCCGTGGAACGACGGCCGCCTTCATAGTCGAGACTCTCGGCCGAGTGCGTTTCACCCGTTGTTACTGCGGCACTAGACGTTCAGTAAGTGTTACATCAAGCGAGTTCATGAACTTCAGCGTAATGGCGTAGAACCTATGCGGCAGTTGCAGCGAAACCTGGGTGTCGTCCCCGGCTACGGTAATCCCTGAGTTAATAGGCAACGAAACATGTTCCGAGCCAAATGTCACGGAACACCGACGGGTACAGAATATTGGGAGCGCACAAATCAGATCCCGCTCGCCGTGAGTTTGAGTCTGTGGGATGGTGAAGCTCCTGTTAGAGTGGTTGGCGGTTCCCAAGTAAGAATGACATTTGACCTGCCCGAATTGCCTTAAGCGGGCGGC"
sc = " "

for letter in s:
    if letter == "A":
        sc += "T"
    elif letter == "T":
        sc += "A"
    elif letter == "C":
        sc += "G"
    elif letter == "G":
        sc += "C"

dnaseq_reversed = sc[::-1]

print(dnaseq_reversed)




