s = "AACGCATACGCCGGTAATCGTATTGGTGCCAGTCAATACAACGTATCGATTAGCCCATACGTAATTCGTCGAATCATCTCCTGTGGGGTTATCCTTGCCAGACTATCGCCACTACCAAGGAGAAGAAATCCACATTGGCCACTTGACGAGTATCCTAGTAGTAAGGTCAATGCGATCAAACGACCTATAAAACGAATGAGCCCACAGGGCATTCTGGCAACTTGAGGGTGGGGACATTCTCACTGGCGGACCGAAAGCCGCACATAGAATCCGCCGATCGGCCATCGAAGGCCTATGGAGTCAGATATCCTATTCACAGCGTCAGTGGTCATTTAAGGGACAGGGGTTTGAGAGCAGGTTTTCTTGCTCTGAGGAAAACTCTTCCGCGGCTCTCCCCACTATCAATCCTTCTGAGGAAATCCCTTGGCGCTCGCCATCGTCGATCGGTGTTTTAAGGTACTCAGTGAGCAGTTCAAGTAGTCTCAGCAACGGTCCGGGAATAAGCCTCCAGGCACCTTGTGAGAAGGCGTGACACTGTATATCCTAGGCGATTCATCTTAGTGCCGTAGCTTTATGTCTCCTTTCACGCACACCGGCAAAAGGTCATTTATACACTGGAGGGCCGTGGACGCCGAGATACACGGACACTTCACGTCGTTGGACCTTTTAAAACCACCCTATTAATCAATGTGCACAAATCGAGGATACCACATACCGCCCCGCCCCGGGTAGCCACGGGTGAAGTTCCCCCCCCCGGTAGATCCATCCACCATCTACCCTTAAGCGCGCATAGCGCCTGGTTAACGGCTCGCGAGATGCAATTCGCACGACTTAAGCTTTCATGACATTGGTGAAACCCCCGGTAGGCCACTCGGTCGTATCAGGAACTCAAAGGTAGACTGTTTAATGGTTTATGGGAAGCCCAAAACCGAGACCTGGAATTCGTACAATAGG"

Tcount = s.count("T")
Acount = s.count("A")
Gcount = s.count("G")
Ccount = s.count("C")

print(s.count("A"), s.count("C"), s.count("G"), s.count("T"))

or

Acount, Ccount, Gcount, Tcount = 0, 0, 0, 0

for letter in s:
     if letter == "A":
             Acount += 1
     elif letter == "C":
             Ccount += 1
     elif letter == "G":
             Gcount += 1
     elif letter == "T":
             Tcount += 1

print(Acount, Ccount, Gcount, Tcount)